CREATE TABLE db_users
         (id INTEGER PRIMARY KEY AUTOINCREMENT,
    username STRING NOT NULL,
       email STRING NOT NULL,
    password STRING NOT NULL,
   create_ts DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
   update_ts DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL);
